version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell

  settings:
    revive:
      rules:
        - name: package-comments

  exclusions:
    presets:
      - comments
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
